// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtqtmcmheazewnpfftty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0cXRtY21oZWF6ZXducGZmdHR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMTg2NzgsImV4cCI6MjA4Mzg5NDY3OH0.9LJ03KJqMJIbqFHesS-UYluHLEf0De75JKkh2DVsut8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});